url: http://rohansadale.github.io
baseurl: /timeline-jekyll-theme

# Site Settings
title: A Mango Person
description: "A personal website of Rohan Sadale."
keywords: "RohanSadale,jekyll,theme,umn"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
